#!/usr/bin/env bun
/**
 * Vendors @earendil-works/pi-coding-agent into packages/cli/tui as the rho
 * agent terminal, using pi's official piConfig rebranding mechanism.
 *
 * Pi resolves its runtime identity (CLI name, config dir, env var prefix) from
 * the nearest package.json above its dist/ tree. The repack writes a generated
 * manifest with piConfig { name: "rho", configDir: ".rho" } next to a verbatim
 * copy of pi's dist, so no pi source changes are needed. `rho agent` spawns
 * tui/dist/cli.js.
 */
import { chmodSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageDir = dirname(dirname(fileURLToPath(import.meta.url)));
const vendorDir = join(packageDir, "tui");
const piEntry = fileURLToPath(import.meta.resolve("@earendil-works/pi-coding-agent"));
const piDir = findPackageDir(piEntry);
const piPackage = JSON.parse(readFileSync(join(piDir, "package.json"), "utf8")) as {
	version?: string;
	dependencies?: Record<string, string>;
};
const piVersion = piPackage.version ?? "unknown";

// Pi's dist imports its runtime dependencies (chalk, undici, ...) from
// node_modules. Declared dependencies are the only resolution every package
// manager (npm, pnpm, bun, yarn) guarantees for files inside a published
// package, so this package mirrors pi's dependency list and the repack fails
// when a pi bump changes it.
const ownPackage = JSON.parse(readFileSync(join(packageDir, "package.json"), "utf8")) as {
	dependencies?: Record<string, string>;
};
const outOfSyncDeps = Object.entries(piPackage.dependencies ?? {})
	.filter(([name, spec]) => ownPackage.dependencies?.[name] !== spec)
	.map(([name, spec]) => `"${name}": "${spec}"`);
if (outOfSyncDeps.length > 0) {
	throw new Error(
		`packages/cli/package.json is out of sync with pi ${piVersion}'s runtime dependencies. ` +
			`Expected: ${outOfSyncDeps.join(", ")}. ` +
			"Sync the dependencies field with @earendil-works/pi-coding-agent, then run bun install.",
	);
}

const stampPath = join(vendorDir, "dist", ".repack-stamp");
if (existsSync(stampPath) && readFileSync(stampPath, "utf8") === piVersion) {
	console.log(`rho agent terminal already repacked from pi ${piVersion}`);
	process.exit(0);
}

rmSync(vendorDir, { recursive: true, force: true });
mkdirSync(vendorDir, { recursive: true });

// Pi's CHANGELOG.md is intentionally not copied: without it, pi skips the
// startup "What's New" display, which would otherwise show pi release notes
// to rho users.
cpSync(join(piDir, "dist"), join(vendorDir, "dist"), { recursive: true });
const docsSource = join(piDir, "docs");
if (existsSync(docsSource)) {
	cpSync(docsSource, join(vendorDir, "docs"), { recursive: true });
}
if (existsSync(join(piDir, "README.md"))) {
	cpSync(join(piDir, "README.md"), join(vendorDir, "PI-README.md"));
}

writeFileSync(
	join(vendorDir, "package.json"),
	`${JSON.stringify(
		{
			name: "rho-agent-tui",
			version: piVersion,
			description:
				"Generated by packages/cli/scripts/repack-tui.ts. The rho agent terminal: a repack of @earendil-works/pi-coding-agent (MIT).",
			type: "module",
			private: true,
			piConfig: {
				name: "rho",
				configDir: ".rho",
			},
		},
		null,
		"\t",
	)}\n`,
);

// User-facing strings in pi's dist that piConfig rebranding does not cover.
// Patterns are anchored on a short stable prefix and replace the whole string
// literal, so wording changes in the rest of the sentence keep matching. A
// miss is a cosmetic leak, so it warns instead of failing the build.
const stringPatches = [
	{
		file: "dist/modes/interactive/interactive-mode.js",
		pattern: /`Pi can explain[^`]*`/,
		replace:
			"`rho can explain its own features and look up its docs. rho is built on the pi coding agent, so everything you can do with pi works here.`",
	},
];
for (const patch of stringPatches) {
	const filePath = join(vendorDir, patch.file);
	const content = readFileSync(filePath, "utf8");
	if (!patch.pattern.test(content)) {
		console.warn(
			`Repack warning: ${patch.file} does not match ${patch.pattern}; pi may have changed its copy. The pi-branded text will show until the pattern is updated.`,
		);
		continue;
	}
	writeFileSync(filePath, content.replace(patch.pattern, patch.replace));
}

chmodSync(join(vendorDir, "dist", "cli.js"), 0o755);
writeFileSync(stampPath, piVersion);
console.log(`Repacked pi ${piVersion} as the rho agent terminal`);

function findPackageDir(startFile: string): string {
	let dir = dirname(startFile);
	while (dir !== dirname(dir)) {
		if (existsSync(join(dir, "package.json"))) {
			return dir;
		}
		dir = dirname(dir);
	}

	throw new Error(`Could not locate pi package.json above ${startFile}`);
}
